name: CI/CD with Slack Alerts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Simulate Build Step
        run: echo "✅ Build successful!"

      - name: Send Slack Notification
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "🚀 CI/CD Job Completed!",
              "attachments": [
                {
                  "text": "*${{ github.repository }}* - `${{ github.workflow }}`\n🔔 Event: `${{ github.event_name }}`\n👤 Triggered by: `${{ github.actor }}`"
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
